cart/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('shop/', include('shop.urls')),
    # path('orders/', include('orders.urls', namespace='orders')),
]   + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    # quantity = forms.TypedChoiceField(label='Количество',
    #                                   choices=PRODUCT_QUANTITY_CHOICES,
    #                                   coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 # quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
            item['update_quantity_form'] = CartAddProductForm(
                              initial={'quantity': item['quantity'],
                              'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends "main/layout.html" %}
{% load static %}

{% block cssblock %}

    <link rel="stylesheet" href="{% static 'cart/css/detail.css' %}">
{% endblock %}

{% block title %}
    Your shopping cart
{% endblock %}

{% block content %}
    <h1>Ваша корзина</h1>
    <table class="cart">
        <thead>
        <tr>
            <th>Изображение</th>
            <th>Товар</th>
            <th>Количество</th>
            <th>Удалить</th>
            <th>Цена одного</th>
            <th>Цена</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <div class="item_product">
                            <a href="{{ product.get_absolute_url }}">
                                {% for key, value in product.image_urs.items %}
                                    {% if key == 'image1' %}
                                        <a href="{{ product.get_absolute_url }}"><img src="{{ value }}"
                                                                                      class="img-thumbnail w-200 h-200"
                                                                                      alt=""></a>
                                    {% endif %}
                                {% endfor %}
                            </a>
                        </div>
                    </td>
                    <td>{{ product.name }}</td>
                    <td>
                        <form action="{% url "cart:cart_add" product.id %}" method="post">
                            {{ item.update_quantity_form.quantity }}
                            {{ item.update_quantity_form.update }}
                            <input type="submit" value="Обновить">
                            {% csrf_token %}
                        </form>
                    </td>
                    <td><a href="{% url "cart:cart_remove" product.id %}">Удалить</a></td>
                    <td class="num">${{ item.price }}</td>
                    <td class="num">${{ item.total_price }}</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <div class="total_info">
            <tr class="total">
                <td>Всего</td>
                <td colspan="4"></td>
                <td class="num">${{ cart.get_total_price }}</td>
            </tr>
        </div>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url "product_list" %}" class="button light">Вернуться в каталог</a>
        {#    <a href="{% url "orders:order_create" %}" class="button">#}
        {#      Купить#}
        {#    </a>#}
    </p>
{% endblock %}